version: "3.9"

services:
  application:
    image: python
    command: /start.sh
    env_file: &envfile
      - .doc.env
    build: &application-build
      context: .
      dockerfile: ./compose/Dockerfile
      args:
        - ENV_TYPE=local
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: on-failure
